### ISSUE TITLE
Can't import DownloadOptions or Notifications

### ISSUE THREAD

**Issue by johnny-stevie** [PolCPP/nativescript-downloadmanager#6]
Can't import both functions from the lib according to IDE, what should I do? Is this an error with the demo app or with the actual lib?

**Comment by jadech32** [comment]
@PolCPP I think the version currently in the repo is inconsistent with the version published, could you publish the version that's currently on master please?

**Comment by johnny-stevie** [comment]
To give closure to the issue. I never solved it. So I dropped working with nativescript and went to the flutter framework instead.
